const sources=[
{name:'Grand Junction Daily Sentinel',region:'Grand Junction / Mesa',home:'https://www.gjsentinel.com/',feed:'https://news.google.com/rss/search?q=site%3Agjsentinel.com+(%22Grand+Junction%22+OR+%22Mesa+County%22+OR+Fruita+OR+Palisade+OR+Clifton+OR+%22Western+Slope%22+OR+%22Western+Colorado%22)&hl=en-US&gl=US&ceid=US%3Aen',stripSuffix:'Grand Junction Daily Sentinel',excludeSports:true},
{name:'KREX / WesternSlopeNow',region:'Grand Junction / Mesa',home:'https://www.westernslopenow.com/',feed:'https://www.westernslopenow.com/feed/'},
{name:'KKCO',region:'Grand Junction / Mesa',home:'https://www.kkco11news.com/',feed:null},{name:'KJCT',region:'Grand Junction / Mesa',home:'https://www.kjct8.com/',feed:null},
{name:'The Business Times — Grand Junction',region:'Grand Junction / Mesa',home:'https://thebusinesstimes.com/',feed:'https://thebusinesstimes.com/feed/'},
{name:'Montrose Daily Press',region:'Montrose / Delta',home:'https://www.montrosepress.com/',feed:'https://www.montrosepress.com/search/?f=rss&t=article&c=news*'},
{name:'Montrose Business Times',region:'Montrose / Delta',home:'https://montrosebusinesstimes.com/',feed:'https://montrosebusinesstimes.com/feed/'},{name:'Delta County Independent',region:'Montrose / Delta',home:'https://www.deltacountyindependent.com/',feed:null},
{name:'Glenwood Springs Post Independent',region:'Glenwood / Garfield',home:'https://www.postindependent.com/',feed:'https://www.postindependent.com/feed/'},
{name:'Aspen Times',region:'Mountains',home:'https://www.aspentimes.com/',feed:'https://www.aspentimes.com/feed/'},{name:'Vail Daily',region:'Mountains',home:'https://www.vaildaily.com/',feed:'https://www.vaildaily.com/feed/'},{name:'Durango Herald',region:'Southwest',home:'https://www.durangoherald.com/',feed:null},
{name:'Colorado Sun',region:'Statewide',home:'https://coloradosun.com/',feed:'https://coloradosun.com/feed/'},{name:'Colorado Public Radio',region:'Statewide',home:'https://www.cpr.org/',feed:'https://www.cpr.org/feed/'},
{name:'Denver Post',region:'Denver / Statewide',home:'https://www.denverpost.com/',feeds:['https://www.denverpost.com/feed/','https://www.denverpost.com/news/feed/','https://www.denverpost.com/news/colorado/feed/']},
{name:'Denver7',region:'Denver / Statewide',home:'https://www.denver7.com/',feed:null},{name:'9NEWS',region:'Denver / Statewide',home:'https://www.9news.com/',feed:null},{name:'CBS Colorado',region:'Denver / Statewide',home:'https://www.cbsnews.com/colorado/',feed:'https://www.cbsnews.com/colorado/latest/rss/main'},{name:'FOX31 Denver',region:'Denver / Statewide',home:'https://kdvr.com/',feed:'https://kdvr.com/feed/'},{name:'Colorado Politics',region:'Statewide',home:'https://www.coloradopolitics.com/',feed:'https://www.coloradopolitics.com/search/?f=rss&t=article&c=news*'}
];
const opinionTerms=['opinion','commentary','editorial','column:','letters to the editor','letter to the editor','guest column','guest commentary','littwin','perspective:'];
const sportsTerms=['sports','football','basketball','baseball','softball','soccer','volleyball','hockey','tennis','golf','wrestling','lacrosse','cross country','track and field','athletics','tournament','championship','playoffs','quarterback','touchdown','home run','pitcher','coach'];
const dec=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,'').trim();
function tag(block,name){const m=block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return m?dec(m[1]):''}
function attr(block,name,attrName){const m=block.match(new RegExp(`<${name}[^>]*${attrName}=["']([^"']+)["'][^>]*>`,'i'));return m?dec(m[1]):''}
function cleanTitle(title,s){if(!s.stripSuffix)return title;return title.replace(new RegExp(`\\s+-\\s+${s.stripSuffix.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}$`,'i'),'').trim()}
function parse(xml,s){let blocks=[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map(m=>m[0]);if(!blocks.length)blocks=[...xml.matchAll(/<entry\b[\s\S]*?<\/entry>/gi)].map(m=>m[0]);return blocks.slice(0,25).map(b=>({source:s.name,region:s.region,title:cleanTitle(tag(b,'title'),s),summary:tag(b,'description')||tag(b,'summary')||tag(b,'content'),category:tag(b,'category'),creator:tag(b,'dc:creator')||tag(b,'author'),url:tag(b,'link')||attr(b,'link','href')||s.home,published:tag(b,'pubDate')||tag(b,'published')||tag(b,'updated'),home:s.home})).filter(i=>i.title)}
async function fetchFeed(url,s){const c=new AbortController();const timer=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 ColoradoNewsDesk/1.0'},signal:c.signal});if(!r.ok)throw Error(r.status);return parse(await r.text(),s)}finally{clearTimeout(timer)}}
function normTitle(title=''){return title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function unique(items){const seenUrls=new Set(),seenTitles=new Set();return items.filter(i=>{const url=(i.url||'').replace(/\?.*$/,'').toLowerCase();const title=normTitle(i.title);if((url&&seenUrls.has(url))||(title&&seenTitles.has(title)))return false;if(url)seenUrls.add(url);if(title)seenTitles.add(title);return true})}
function isOpinion(i){const text=`${i.title} ${i.category} ${i.creator} ${i.url}`.toLowerCase();return opinionTerms.some(t=>text.includes(t))}
function isSports(i){const text=`${i.title} ${i.category} ${i.summary} ${i.url}`.toLowerCase();return sportsTerms.some(t=>text.includes(t))}
async function one(s){const feeds=s.feeds||[s.feed];if(!feeds[0])return{source:s.name,region:s.region,home:s.home,status:'source-only',items:[]};let all=[];for(const feed of feeds){try{all.push(...await fetchFeed(feed,s))}catch{}}all=unique(all).filter(i=>!isOpinion(i));if(s.excludeSports)all=all.filter(i=>!isSports(i));all.sort((a,b)=>new Date(b.published||0)-new Date(a.published||0));all=all.slice(0,3).map(({summary,category,creator,...i})=>i);return{source:s.name,region:s.region,home:s.home,status:all.length?'ok':'unavailable',items:all}}
module.exports=async(req,res)=>{const results=await Promise.all(sources.map(one));res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.status(200).json({updated:new Date().toISOString(),results})};