const newsSearch=domain=>`https://news.google.com/rss/search?q=${encodeURIComponent(`site:${domain} when:3d`)}&hl=en-US&gl=US&ceid=US:en`;
const sources=[
{name:'Montrose Press',region:'Montrose / Delta',home:'https://www.montrosepress.com/',feeds:['https://www.montrosepress.com/search/?f=rss&t=article&c=news*',newsSearch('montrosepress.com')]},
{name:'Glenwood Post Independent',region:'Glenwood / Garfield',home:'https://www.postindependent.com/',feeds:['https://www.postindependent.com/feed/',newsSearch('postindependent.com')]},
{name:'Aspen Daily News',region:'Mountains',home:'https://www.aspendailynews.com/',feeds:['https://www.aspendailynews.com/search/?f=rss&t=article&c=news*',newsSearch('aspendailynews.com')]},
{name:'Denver Post',region:'Denver / Statewide',home:'https://www.denverpost.com/',feeds:['https://www.denverpost.com/feed/','https://www.denverpost.com/news/colorado/feed/',newsSearch('denverpost.com')]},
{name:'Colorado Sun',region:'Statewide',home:'https://coloradosun.com/',feed:'https://coloradosun.com/feed/'},
{name:'KCNC-TV / CBS Colorado',region:'Denver / Statewide',home:'https://www.cbsnews.com/colorado/',feed:'https://www.cbsnews.com/colorado/latest/rss/main'},
{name:'KDVR-TV / FOX31',region:'Denver / Statewide',home:'https://kdvr.com/',feeds:['https://kdvr.com/feed/',newsSearch('kdvr.com')]},
{name:'KUSA-TV / 9NEWS',region:'Denver / Statewide',home:'https://www.9news.com/',feeds:['https://www.9news.com/feeds/syndication/rss/news/local',newsSearch('9news.com')]},
{name:'KMGH-TV / Denver7',region:'Denver / Statewide',home:'https://www.denver7.com/',feeds:['https://www.denver7.com/news/local-news.rss',newsSearch('denver7.com')]},
{name:'Colorado Public Radio',region:'Statewide',home:'https://www.cpr.org/',feeds:['https://www.cpr.org/feed/',newsSearch('cpr.org')]},
{name:'Colorado Newsline',region:'Statewide',home:'https://coloradonewsline.com/',feeds:['https://coloradonewsline.com/feed/',newsSearch('coloradonewsline.com')]}
];
const opinionTerms=['opinion','commentary','editorial','column:','columns','letters to the editor','letter to the editor','guest column','guest commentary','littwin','perspective:','our view','their view','your view','reader view','from the editor','editor’s note','editors note','sound off','speak out','letters:','letter:'];
const sportsTerms=['sports','football','basketball','baseball','softball','soccer','volleyball','hockey','tennis','golf','wrestling','lacrosse','cross country','track and field','athletics','tournament','championship','playoffs','quarterback','touchdown','home run','pitcher','coach'];
const religionTerms=['religion','religious','church','faith','ministry','ministries','pastor','worship','christian','catholic','baptist','methodist','presbyterian','lutheran','episcopal','mormon','lds','gospel','bible'];
const dec=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,'').trim();
function tag(block,name){const m=block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return m?dec(m[1]):''}
function attr(block,name,attrName){const m=block.match(new RegExp(`<${name}[^>]*${attrName}=["']([^"']+)["'][^>]*>`,'i'));return m?dec(m[1]):''}
function cleanTitle(title,s){if(!s.stripSuffix)return title;return title.replace(new RegExp(`\\s+-\\s+${s.stripSuffix.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}$`,'i'),'').trim()}
function parse(xml,s){let blocks=[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map(m=>m[0]);if(!blocks.length)blocks=[...xml.matchAll(/<entry\b[\s\S]*?<\/entry>/gi)].map(m=>m[0]);return blocks.slice(0,50).map(b=>({source:s.name,region:s.region,title:cleanTitle(tag(b,'title'),s),summary:tag(b,'description')||tag(b,'summary')||tag(b,'content'),category:tag(b,'category'),creator:tag(b,'dc:creator')||tag(b,'author'),url:tag(b,'link')||attr(b,'link','href')||s.home,published:tag(b,'pubDate')||tag(b,'published')||tag(b,'updated'),home:s.home})).filter(i=>i.title)}
async function fetchFeed(url,s){const c=new AbortController();const timer=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 ColoradoNewsDesk/1.0'},signal:c.signal});if(!r.ok)throw Error(r.status);return parse(await r.text(),s)}finally{clearTimeout(timer)}}
function normTitle(title=''){return title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function unique(items){const seenUrls=new Set(),seenTitles=new Set();return items.filter(i=>{const url=(i.url||'').replace(/\?.*$/,'').toLowerCase();const title=normTitle(i.title);if((url&&seenUrls.has(url))||(title&&seenTitles.has(title)))return false;if(url)seenUrls.add(url);if(title)seenTitles.add(title);return true})}
function isOpinion(i){const text=`${i.title} ${i.category} ${i.creator} ${i.url}`.toLowerCase();return opinionTerms.some(t=>text.includes(t))}
function isStrictOpinion(i){const title=(i.title||'').toLowerCase().trim();const text=`${i.title} ${i.category} ${i.creator} ${i.summary}`.toLowerCase();if(isOpinion(i))return true;if(/^(letter|letters|opinion|editorial|commentary|column|our view|their view|your view|reader view|sound off|speak out)\b[:\s-]*/i.test(title))return true;if(/\b(letter|letters)\s+(to|from)\b/.test(text))return true;if(/\b(op-ed|oped)\b/.test(text))return true;return false}
function isSports(i){const text=`${i.title} ${i.category} ${i.summary} ${i.url}`.toLowerCase();return sportsTerms.some(t=>text.includes(t))}
function isReligion(i){const text=`${i.title} ${i.category} ${i.summary} ${i.url}`.toLowerCase();return religionTerms.some(t=>text.includes(t))}
async function one(s){const feeds=s.feeds||[s.feed];if(!feeds[0])return{source:s.name,region:s.region,home:s.home,status:'source-only',items:[]};let all=(await Promise.all(feeds.map(feed=>fetchFeed(feed,s).catch(()=>[])))).flat();all=unique(all).filter(i=>s.strictOpinion?!isStrictOpinion(i):!isOpinion(i));if(s.excludeSports)all=all.filter(i=>!isSports(i));if(s.excludeReligion)all=all.filter(i=>!isReligion(i));all.sort((a,b)=>new Date(b.published||0)-new Date(a.published||0));all=all.slice(0,5).map(({summary,category,creator,...i})=>i);return{source:s.name,region:s.region,home:s.home,status:all.length?'ok':'source-only',items:all}}
module.exports=async(req,res)=>{const results=await Promise.all(sources.map(one));res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.status(200).json({updated:new Date().toISOString(),results})};
